create table if not exists public.paulista_products (
  id text primary key,
  name text not null,
  category text not null,
  description text default '',
  price numeric(10,2) not null default 0,
  sizes jsonb,
  is_pizza boolean not null default false,
  sold_out boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.paulista_orders (
  id text primary key,
  order_number bigint generated by default as identity,
  created_at timestamptz not null default now(),
  source text not null,
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  payment text not null,
  change_for numeric(10,2) not null default 0,
  notes text default '',
  printed boolean not null default false,
  printed_at timestamptz,
  status text not null default 'Novo'
);

create table if not exists public.paulista_categories (
  name text primary key,
  display_order integer not null default 999,
  created_at timestamptz not null default now()
);

alter table public.paulista_products enable row level security;
alter table public.paulista_orders enable row level security;
alter table public.paulista_categories enable row level security;

drop policy if exists "paulista products read" on public.paulista_products;
drop policy if exists "paulista products write" on public.paulista_products;
drop policy if exists "paulista orders read" on public.paulista_orders;
drop policy if exists "paulista orders insert" on public.paulista_orders;
drop policy if exists "paulista orders update" on public.paulista_orders;
drop policy if exists "paulista categories read" on public.paulista_categories;
drop policy if exists "paulista categories write" on public.paulista_categories;

create policy "paulista products read"
on public.paulista_products for select
to anon
using (true);

create policy "paulista products write"
on public.paulista_products for all
to anon
using (true)
with check (true);

create policy "paulista orders read"
on public.paulista_orders for select
to anon
using (true);

create policy "paulista orders insert"
on public.paulista_orders for insert
to anon
with check (true);

create policy "paulista orders update"
on public.paulista_orders for update
to anon
using (true)
with check (true);

create policy "paulista categories read"
on public.paulista_categories for select
to anon
using (true);

create policy "paulista categories write"
on public.paulista_categories for all
to anon
using (true)
with check (true);

create or replace function public.touch_paulista_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists paulista_products_touch_updated_at on public.paulista_products;

create trigger paulista_products_touch_updated_at
before update on public.paulista_products
for each row execute function public.touch_paulista_updated_at();
